import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/ui/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Your Digital Flower",
  description: "Discover your unique digital flower generated by your seed.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} antialiased h-full w-full bg-[#fcfcfc] text-zinc-900 selection:bg-zinc-900 selection:text-white`}>
      <body suppressHydrationWarning className="flex min-h-full flex-col font-sans">
        <Navbar />
        <main className="flex-1 flex flex-col pt-16 sm:pt-20 md:pt-24 pb-8 sm:pb-12 px-3 sm:px-6">
          <div className="flex-1 flex flex-col w-full max-w-5xl mx-auto items-center justify-center">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
